### ISSUE TITLE
zos-lib not working in browser

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#793] opened 2019-03-26 15:54 UTC
This issue has been raised in this zeppelin forum [thread](https://forum.zeppelin.solutions/t/zos-lib-cant-be-used-in-the-browser/439).
It seems that webpack si not being able to resolve some libraries that `zos-lib` depends on, for instance `glob` or `truffle-flattener`.
I tried to test this in a new react app, and after importing some `zos-lib` classes, webpack throws the following:

```
WARNING in ./node_modules/zos-lib/lib/artifacts/Contracts.js 82:23-42
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in '/home/jota/zeppelin/examples/react-example/node_modules/fs.realpath'
 @ ./node_modules/fs.realpath/index.js 8:9-22
 @ ./node_modules/zos-lib/node_modules/glob/glob.js
 @ ./node_modules/zos-lib/lib/artifacts/Contracts.js
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in '/home/jota/zeppelin/examples/react-example/node_modules/fs.realpath'
 @ ./node_modules/fs.realpath/old.js 24:9-22
 @ ./node_modules/fs.realpath/index.js
 @ ./node_modules/zos-lib/node_modules/glob/glob.js
 @ ./node_modules/zos-lib/lib/artifacts/Contracts.js
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/zos-lib/lib/utils/FileSystem.js
Module not found: Error: Can't resolve 'fs' in '/home/jota/zeppelin/examples/react-example/node_modules/zos-lib/lib/utils'
 @ ./node_modules/zos-lib/lib/utils/FileSystem.js 6:29-42
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/zos-lib/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in '/home/jota/zeppelin/examples/react-example/node_modules/zos-lib/node_modules/glob'
 @ ./node_modules/zos-lib/node_modules/glob/glob.js 43:9-22
 @ ./node_modules/zos-lib/lib/artifacts/Contracts.js
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/zos-lib/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in '/home/jota/zeppelin/examples/react-example/node_modules/zos-lib/node_modules/glob'
 @ ./node_modules/zos-lib/node_modules/glob/sync.js 4:9-22
 @ ./node_modules/zos-lib/node_modules/glob/glob.js
 @ ./node_modules/zos-lib/lib/artifacts/Contracts.js
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js

ERROR in ./node_modules/truffle-flattener/index.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #! /usr/bin/env node
| 
| "use strict";
 @ ./node_modules/zos-lib/lib/utils/Solidity.js 6:44-72
 @ ./node_modules/zos-lib/lib/index.js
 @ ./src/containers/navbar.js
 @ ./src/containers/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js
ℹ ｢wdm｣: Failed to compile.

```

We should do some research on how we can fix this issue, as using `zos-lib` in a browser environment could be extremely useful for managing, creating and updating contract instances within a DApp.

**Comment by spalladino** [comment] 2019-12-11 20:38
Closing as duplicate of #808

**Closed by spalladino** 2019-12-11 20:38 UTC
Labels: component:lib, kind:bug
