### ISSUE TITLE
`zos balance` fails silently if there is something wrong with config

### ISSUE THREAD

**Issue by ylv-io** [OpenZeppelin/openzeppelin-sdk#997] opened 2019-06-18 20:46 UTC
![image](https://user-images.githubusercontent.com/3285000/59718615-33147480-9223-11e9-8159-3b07407e25d1.png)

I think my INFURA key is outdated but not sure what is exactly wrong. We should provide at least some feedback if request failed.

**Comment by ylv-io** [comment] 2019-06-18 22:32
Can confirm that issue happens if you have invalid API key.

**Comment by jcarpanelli** [comment] 2019-06-24 15:56
Also, this can be happening due to specifying the `infura` url using `http` instead of `https`.

**Comment by spalladino** [comment] 2019-12-13 15:02
We got [another report](https://forum.openzeppelin.com/t/problems-deploying-to-kovan-crash-and-not-asking-for-initialize-function/1926) in the forum:
> PS: quick feedback, earlier when trying to deploy it failed silently after picking network in the create prompt. Turns out my dumb ass was using an incorrect Infura URL, but adding a “Network Error” message or similar in the cli would help.

**Comment by nventuro** [comment] 2019-12-13 21:35
It looks like the bug is on truffle's end: when `web3.eth().net.getId()` is called with a backing hdwallet-provider and an invalid Infura API key, the process immediately exits. This is very likely related to https://github.com/trufflesuite/truffle/issues/2655

I was able to reproduce the same behaviour on a barebones truffle project. Given the following config file, `truffle console --network mainnet` also exits ungracefully.

```
const HDWalletProvider = require('@truffle/hdwallet-provider');
const invalidInfuraId = 'abcdinvalid';
const mnemonic = 'absorb fork spin mercy intact coast either you viable broccoli rain craft';

module.exports = {
  networks: {
    mainnet: {
      provider: () => new HDWalletProvider(mnemonic, "https://mainnet.infura.io/v3/" + invalidInfuraId),
      network_id: '1',
    },
  },
}
```

**Comment by spalladino** [comment] 2019-12-13 21:54
Good finding @nventuro. Nothing we can do on our end, it's once again faulty dependencies. Closing!

**Closed by spalladino** 2019-12-13 21:54 UTC
Labels: kind:bug, status:hot, topic:interacting
