### ISSUE TITLE
zos link zos-lib feels more natural than npm install zos-lib

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#776] opened 2019-03-09 12:38 UTC
Small thing: It feels like if we are using zos link to install via npm EVM packages, it would be nice for zos-lib to also be installable through zos-link, even though it doesn't have a zos.json package. This feels more natural in the context of doing "zos link" for things directly related to using zeppelinOS.

**Comment by jcarpanelli** [comment] 2019-03-09 15:30
I think that this could be a bit weird, as `zos-lib` is not an EVM package itself and thus installing it through `zos link` (which will run `npm install zos-lib` and do the trick) could create some confusion. Nevertheless, I get the point that the fact of having to install both `zos-lib` locally and `zos` globally could be somewhat annoying and also confusing.
A good approach to get rid of having to ask the user to install both packages separately would be to ask them to install `zos` locally instead of globally. (i.e., running `npm install zos` instead of running `npm install -g zos`). As `zos` depends on `zos-lib`, the user will have `zos-lib` available for importing, for instance, `Initializable.sol` inside their contracts without having to install it separately. Additionally, installing `zos` locally could be also a good idea as the user's environment will be reproducible and future version conflicts could be avoided.
note: I'm labeling this issue as `kind:documentation` as this could change the way we explain the users how to use `zos` (prepending `npx`, e.g., `npx zos push --network mainnet`)

**Comment by spalladino** [comment] 2019-12-11 20:50
Closing due to #1314

**Closed by spalladino** 2019-12-11 20:50 UTC
Labels: component:lib, kind:documentation, kind:idea
