### ISSUE TITLE
Bug: When choosing non-upgradable proxy, CLI offers to upgrade it. 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#1571] opened 2020-07-31 14:43 UTC
When deploying a non-upgradable minimal proxy, the OZ Cli after deployment tells me that to upgrade the instance I use 'oz upgrade'. 

This is confusing messaging when I have just selected a specifically non-upgradable proxy. 
<img width="606" alt="Screen Shot 2020-07-31 at 10 41 18 AM" src="https://user-images.githubusercontent.com/1938013/89046261-b3f4d980-d31a-11ea-8369-7c27144d7dde.png">

**Comment by frangio** [comment] 2020-08-03 20:20
Thank you for the feedback @crazyrabbitLTC! :smile:

Closing this as a duplicate of https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1543.

**Closed by frangio** 2020-08-03 20:20 UTC
